version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for static frontend"

  build:
    commands:
      - echo "No build step needed for static site"

  post_build:
    commands:
      - echo "Deploying static site to S3..."
      - aws s3 sync ./Frontend/ s3://cloudresume-portfolio --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id d20dywo6lz1slm --paths "/*"

artifacts:
  files:
    - '**/*'
