AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AccountID: { Type: String }
Resources:
  ApiGatewayLogRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: APIGatewayCloudWatchLogsRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
Outputs:
  ApiGatewayLogRoleArn:
    Value: !GetAtt ApiGatewayLogRole.Arn
