AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ApiId: { Type: String }
  VisitorLambdaName: { Type: String }
Resources:
  PermissionForApi:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VisitorLambdaName
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*/GET/

Outputs:
  ApiInvokeURL:
    Value: !Sub https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/dev/
