AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ResumeTableName: { Type: String }
Resources:
  ResumeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ResumeTableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
Outputs:
  TableName:
    Value: !Ref ResumeTable
