AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3BucketName: { Type: String }
  CloudFrontDomain: { Type: String }
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

Outputs:
  CloudFrontUrl:
    Value: !Sub https://${CloudFrontDomain}
