AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ResumeTableName: { Type: String }
  VisitorLambdaName: { Type: String }
  SNSTopicArn: { Type: String }
Resources:
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: order-error
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref VisitorLambdaName
      Statistic: Sum
      Period: 60
      Threshold: 1
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SNSTopicArn
      TreatMissingData: notBreaching
